[build]
  command = "npm ci --no-optional && npm run build"
  publish = "dist"

[context.production.environment]
  CI = "false"
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
